"""Add indexes on Detection, Camera, AuthUser

Revision ID: 8e364d72eda0
Revises: 003
Create Date: 2026-04-01 16:19:35.144548

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8e364d72eda0'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('alerts', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('alerts', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.alter_column('auth_users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('auth_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('auth_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_auth_users_role'), 'auth_users', ['role'], unique=False)
    op.alter_column('cameras', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('cameras', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('cameras', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_cameras_status'), 'cameras', ['status'], unique=False)
    op.alter_column('detections', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_detections_camera_id'), 'detections', ['camera_id'], unique=False)
    op.create_index('ix_detections_camera_timestamp', 'detections', ['camera_id', 'timestamp'], unique=False)
    op.create_index('ix_detections_status', 'detections', ['status'], unique=False)
    op.create_index(op.f('ix_detections_timestamp'), 'detections', ['timestamp'], unique=False)
    op.alter_column('objects', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('unknown_faces', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('unknown_faces', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('objects', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_detections_timestamp'), table_name='detections')
    op.drop_index('ix_detections_status', table_name='detections')
    op.drop_index('ix_detections_camera_timestamp', table_name='detections')
    op.drop_index(op.f('ix_detections_camera_id'), table_name='detections')
    op.alter_column('detections', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_cameras_status'), table_name='cameras')
    op.alter_column('cameras', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('cameras', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('cameras', 'status',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index(op.f('ix_auth_users_role'), table_name='auth_users')
    op.alter_column('auth_users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('auth_users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('auth_users', 'role',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.alter_column('alerts', 'timestamp',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('alerts', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('alerts', 'severity',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    # ### end Alembic commands ###
